name: GPT Code Review

on: 
  pull_request:
permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - uses: GrantBirki/git-diff-action@v2.4.0
      id: git_diff
      with:
        raw_diff_file_output: diff.txt
        file_output: "true"

    - name: Perform Code Review With gpt-4
      id: code_review_suggestions
      run: |
        changed_code=$(cat ${{steps.git_diff.outputs.raw-diff-path}})
        echo "PR Diff: $changed_code"

