name: GPT Code Review

on: 
  pull_request:
permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - uses: GrantBirki/git-diff-action@v2.4.0
      id: git_diff
      with:
        raw_diff_file_output: diff.txt
        file_output: "true"

    - name: Perform Code Review With gpt-4
      id: code_review_suggestions
      env:
        CODE_REVIEW_PROMPT: "Review the following code changes and provide suggestions for improvement."
      run: |
        changed_code=$(cat ${{steps.git_diff.outputs.diff_file}})
        echo "PR Diff: $changed_code"
        escaped_code=$(echo "$changed_code" | jq -s -R -r @json)
        response=$(curl https://api.openai.com/v1/chat/completions  \
         -H "Content-Type: application/json"  \
         -H "Authorization: Bearer ${{secrets.OPEN_AI_KEY}}"  \
         -d '{
          "model": "gpt-4",
          "messages": [
            {
              "role": "system",
              "content": "'"${CODE_REVIEW_PROMPT}"'"
            },
            {
              "role": "user",
              "content": '$escaped_code'
            }
          ]
        }')

        echo "This is the response: $response"
        echo_review_suggestions=$(echo $response | jq -r '.choices[0].message.content')
        echo "$echo_review_suggestions" > code_suggestions.txt

    - name: Add Code Suggestion Comment
      run: |
        cat code_suggestions.txt
        escaped_comments=$(echo "$(cat code_suggestions.txt | jq -s -R -r @json)
        curl -L \
        -X POST \
        -H \"Authorization: token ${{secrets.GIT_TOKEN}}\" \
        -H \"X-GithHub-Api-Version 2022-11-28\" \
        https://api.github.com/repos/${{github.repository}}/issues/${{github.event.pull_request.number}}/comments \
        -d \'{
          \"body\": $escaped_comments
        }\'